//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace k22cntt3pvv2210900085.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pvv2210900085Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pvv2210900085Entities object using the connection string found in the 'pvv2210900085Entities' section of the application configuration file.
        /// </summary>
        public pvv2210900085Entities() : base("name=pvv2210900085Entities", "pvv2210900085Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pvv2210900085Entities object.
        /// </summary>
        public pvv2210900085Entities(string connectionString) : base(connectionString, "pvv2210900085Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pvv2210900085Entities object.
        /// </summary>
        public pvv2210900085Entities(EntityConnection connection) : base(connection, "pvv2210900085Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PvvCategory> PvvCategory
        {
            get
            {
                if ((_PvvCategory == null))
                {
                    _PvvCategory = base.CreateObjectSet<PvvCategory>("PvvCategory");
                }
                return _PvvCategory;
            }
        }
        private ObjectSet<PvvCategory> _PvvCategory;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PvvProduct> PvvProduct
        {
            get
            {
                if ((_PvvProduct == null))
                {
                    _PvvProduct = base.CreateObjectSet<PvvProduct>("PvvProduct");
                }
                return _PvvProduct;
            }
        }
        private ObjectSet<PvvProduct> _PvvProduct;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PvvCategory EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPvvCategory(PvvCategory pvvCategory)
        {
            base.AddObject("PvvCategory", pvvCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PvvProduct EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPvvProduct(PvvProduct pvvProduct)
        {
            base.AddObject("PvvProduct", pvvProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pvv2210900085Model", Name="PvvCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PvvCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PvvCategory object.
        /// </summary>
        /// <param name="pvvID">Initial value of the PvvID property.</param>
        public static PvvCategory CreatePvvCategory(global::System.Int32 pvvID)
        {
            PvvCategory pvvCategory = new PvvCategory();
            pvvCategory.PvvID = pvvID;
            return pvvCategory;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PvvID
        {
            get
            {
                return _PvvID;
            }
            set
            {
                if (_PvvID != value)
                {
                    OnPvvIDChanging(value);
                    ReportPropertyChanging("PvvID");
                    _PvvID = StructuralObject.SetValidValue(value, "PvvID");
                    ReportPropertyChanged("PvvID");
                    OnPvvIDChanged();
                }
            }
        }
        private global::System.Int32 _PvvID;
        partial void OnPvvIDChanging(global::System.Int32 value);
        partial void OnPvvIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PvvCateName
        {
            get
            {
                return _PvvCateName;
            }
            set
            {
                OnPvvCateNameChanging(value);
                ReportPropertyChanging("PvvCateName");
                _PvvCateName = StructuralObject.SetValidValue(value, true, "PvvCateName");
                ReportPropertyChanged("PvvCateName");
                OnPvvCateNameChanged();
            }
        }
        private global::System.String _PvvCateName;
        partial void OnPvvCateNameChanging(global::System.String value);
        partial void OnPvvCateNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PvvStatus
        {
            get
            {
                return _PvvStatus;
            }
            set
            {
                OnPvvStatusChanging(value);
                ReportPropertyChanging("PvvStatus");
                _PvvStatus = StructuralObject.SetValidValue(value, "PvvStatus");
                ReportPropertyChanged("PvvStatus");
                OnPvvStatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _PvvStatus;
        partial void OnPvvStatusChanging(Nullable<global::System.Boolean> value);
        partial void OnPvvStatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pvv2210900085Model", Name="PvvProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PvvProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PvvProduct object.
        /// </summary>
        /// <param name="pvvid2210900085">Initial value of the Pvvid2210900085 property.</param>
        public static PvvProduct CreatePvvProduct(global::System.String pvvid2210900085)
        {
            PvvProduct pvvProduct = new PvvProduct();
            pvvProduct.Pvvid2210900085 = pvvid2210900085;
            return pvvProduct;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pvvid2210900085
        {
            get
            {
                return _Pvvid2210900085;
            }
            set
            {
                if (_Pvvid2210900085 != value)
                {
                    OnPvvid2210900085Changing(value);
                    ReportPropertyChanging("Pvvid2210900085");
                    _Pvvid2210900085 = StructuralObject.SetValidValue(value, false, "Pvvid2210900085");
                    ReportPropertyChanged("Pvvid2210900085");
                    OnPvvid2210900085Changed();
                }
            }
        }
        private global::System.String _Pvvid2210900085;
        partial void OnPvvid2210900085Changing(global::System.String value);
        partial void OnPvvid2210900085Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PvvProName
        {
            get
            {
                return _PvvProName;
            }
            set
            {
                OnPvvProNameChanging(value);
                ReportPropertyChanging("PvvProName");
                _PvvProName = StructuralObject.SetValidValue(value, true, "PvvProName");
                ReportPropertyChanged("PvvProName");
                OnPvvProNameChanged();
            }
        }
        private global::System.String _PvvProName;
        partial void OnPvvProNameChanging(global::System.String value);
        partial void OnPvvProNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PvvQty
        {
            get
            {
                return _PvvQty;
            }
            set
            {
                OnPvvQtyChanging(value);
                ReportPropertyChanging("PvvQty");
                _PvvQty = StructuralObject.SetValidValue(value, "PvvQty");
                ReportPropertyChanged("PvvQty");
                OnPvvQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _PvvQty;
        partial void OnPvvQtyChanging(Nullable<global::System.Int32> value);
        partial void OnPvvQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PvvPrice
        {
            get
            {
                return _PvvPrice;
            }
            set
            {
                OnPvvPriceChanging(value);
                ReportPropertyChanging("PvvPrice");
                _PvvPrice = StructuralObject.SetValidValue(value, "PvvPrice");
                ReportPropertyChanged("PvvPrice");
                OnPvvPriceChanged();
            }
        }
        private Nullable<global::System.Double> _PvvPrice;
        partial void OnPvvPriceChanging(Nullable<global::System.Double> value);
        partial void OnPvvPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PvvCateId
        {
            get
            {
                return _PvvCateId;
            }
            set
            {
                OnPvvCateIdChanging(value);
                ReportPropertyChanging("PvvCateId");
                _PvvCateId = StructuralObject.SetValidValue(value, "PvvCateId");
                ReportPropertyChanged("PvvCateId");
                OnPvvCateIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PvvCateId;
        partial void OnPvvCateIdChanging(Nullable<global::System.Int32> value);
        partial void OnPvvCateIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PvvActive
        {
            get
            {
                return _PvvActive;
            }
            set
            {
                OnPvvActiveChanging(value);
                ReportPropertyChanging("PvvActive");
                _PvvActive = StructuralObject.SetValidValue(value, "PvvActive");
                ReportPropertyChanged("PvvActive");
                OnPvvActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _PvvActive;
        partial void OnPvvActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnPvvActiveChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pvv2210900085Model", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }

    #endregion

}
